[W  8][CS2103AUG2017-F11-B2]Jiasheng
CS2103AUG2017-F11-B2/main pull request #41
Opened 2017-10-11 13:49 UTC by AngularJiaSheng

Full implementation and documentation for Tag Delete. However, System test still not done.

2017-10-12 04:15 UTC, hansiang93 commented
Gonna have to wait till all tests are written before merging

2017-10-12 17:22 UTC, zhoukai07 commented on src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
> +    public static final String COMMAND_ALIAS = "t";
I don't think "t" is a clear label for tagDelete, perhaps using "td" would be better?

2017-10-12 17:31 UTC, zhoukai07 commented on src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
> +            if (lengthOfUserInput > 2 || lengthOfUserInput <= 1) {
is it the same as "if (lengthOfUserInput != 2)" ?
did you consider trimming the args first?

2017-10-12 17:33 UTC, zhoukai07 requested changes
hey I think these are some minor changes that could be done.

2017-10-13 09:37 UTC, AngularJiaSheng commented
oh man i think i just screwed everything up OMGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG

2017-10-13 09:42 UTC, closed without merging